### ISSUE TITLE
Demo中的loadData，设置了缓存10秒，抓包看会有连续两次请求。

### ISSUE THREAD

**Issue by sushiwu** [kenshincui/AlamofireURLCache#1]
Demo中的loadData，设置了缓存10秒，抓包看会有连续两次请求。refreshCache之后再次loadData还是会连续发两次请求之后缓存才生效。
![image](https://user-images.githubusercontent.com/5301947/30791418-dc18e47a-a1e4-11e7-9e4a-fec2446b804d.png)
![image](https://user-images.githubusercontent.com/5301947/30791459-3412ef04-a1e5-11e7-9a30-5a6647d5cd5f.png)

**Comment by kenshincui** [comment]
There may be a certain delay in urlcache in different versions, I cannot reproduce this problem now, you can upgrade to the latest version

**Comment by kenshincui** [comment]
If there is no problem, the problem is closed

**Comment by kenshincui** [comment]
fixed
