### ISSUE TITLE
Cached response does not return 304

### ISSUE THREAD

**Issue by ratzr15** [kenshincui/AlamofireURLCache#2]
As per the usage and requesting 
`Alamofire.request(url,refreshCache:false).responseJSON(completionHandler: { response in
            if response.value != nil {
            } else {
            }
        }).cache(maxAge: 10)`

If we check the **statusCode** of the response it does not _return 304_

**Comment by kenshincui** [comment]
304 is the server-side status. If the local cache is valid, it will not be requested again. This is also the meaning of cache
