### ISSUE TITLE
Can not find 'AlamofireURLCache5' in pod search

### ISSUE THREAD

**Issue by conversun** [kenshincui/AlamofireURLCache#4]
![20201025152632-6FdDXr](https://cdn.jsdelivr.net/gh/conversun/statics@master/images/20201025152632-6FdDXr.png)

**Comment by kenshincui** [comment]
Thanks for your feedback, AlamofireURLCache5 is now available, please try again. Note that AlamofireURLCache5 is not AlamofireURLCache. The link address is https://cocoapods.org/pods/AlamofireURLCache5
